In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Loading the Diabetes dataset
diabetes_data = load_diabetes(as_frame=True)
df = diabetes_data.frame

In [3]:
# Displaying the first few rows of the dataset
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [4]:
# Creating a binary target variable by applying a threshold on the 'target' feature
# etting threshold to 140, meaning if value > 140, we classify as 1 (diabetes), else 0 (no diabetes)
df['diabetes_status'] = df['target'].apply(lambda x : 1 if x > 140 else 0)

# Droppimh the original target column 
df = df.drop(columns=['target'])

In [5]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,diabetes_status
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,1
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,1
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,1
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,0

In [6]:
# Splitting the data into features and target variable
x = df.drop(columns=['diabetes_status'])
y = df['diabetes_status']

# Splitting into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [7]:
# Initializing and training the RandomForestClassifier
model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [8]:
# Making predictions on the test set
y_pred = model.predict(x_test)

# Calculating accuracy and generating classification report
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Displaying the results
print(f"Accuracy : {accuracy * 100:.2f}%")
print("\nClassification Report : \n", report)
print("\nConfusion Matrix : \n", conf_matrix)

Accuracy : 75.19%

Classification Report :
               precision    recall  f1-score   support

           0       0.80      0.72      0.76        72
           1       0.71      0.79      0.74        61

    accuracy                           0.75       133
   macro avg       0.75      0.75      0.75       133
weighted avg       0.76      0.75      0.75       133


Confusion Matrix :
 [[52 20]
 [13 48]]

In [9]:
# Getting feature importance from the RandomForestClassifier
feature_importances = pd.DataFrame({'feature' : x.columns, 'importance' : model.feature_importances_})
feature_importances = feature_importances.sort_values(by='importance', ascending=False)

# Display feature importances
feature_importances

  feature  importance
2     bmi    0.208397
8      s5    0.135383
3      bp    0.126268
9      s6    0.096754
6      s3    0.096437
5      s2    0.091537
4      s1    0.088727
0     age    0.079116
7      s4    0.056682
1     sex    0.020699